version: '3.5'
services:
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    container_name: databaseMySQL
    restart: always
    environment:
      MYSQL_DATABASE: 'passwordapidb'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'      
      MYSQL_ROOT_PASSWORD: 'rootpass'
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume: